"""
Tests for CLI entry point (move_calibration.py main()).
Verifies argument parsing and main() integration.

Following CLI Testing Standards to prevent argparse attribute bugs.

Generated By: Claude Code (Claude Sonnet 4.5)
"""

import pytest
from ap_move_master_to_library.move_calibration import main, EXIT_SUCCESS


class TestMainCLI:
    """Tests for main() CLI entry point.

    Following CLI Testing Standards to verify argparse attribute mapping.
    Prevents runtime AttributeError from typos in args.attribute_name access.
    """

    def test_minimal_execution(self, tmp_path, mocker):
        """Test minimal required arguments (source_dir, dest_dir)."""
        source = tmp_path / "source"
        dest = tmp_path / "dest"
        source.mkdir()
        dest.mkdir()

        mock_copy = mocker.patch(
            "ap_move_master_to_library.move_calibration.copy_calibration_frames"
        )

        mocker.patch(
            "sys.argv",
            ["ap-move-master-to-library", str(source), str(dest)],
        )

        main()

        # Verify copy_calibration_frames was called with correct kwargs
        call_args = mock_copy.call_args
        assert call_args.kwargs["source_dir"] == str(source)
        assert call_args.kwargs["dest_dir"] == str(dest)
        assert call_args.kwargs["debug"] is False
        assert call_args.kwargs["dryrun"] is False
        assert call_args.kwargs["no_overwrite"] is False

    def test_debug_flag(self, tmp_path, mocker):
        """Test --debug flag is correctly passed."""
        source = tmp_path / "source"
        dest = tmp_path / "dest"
        source.mkdir()
        dest.mkdir()

        mock_copy = mocker.patch(
            "ap_move_master_to_library.move_calibration.copy_calibration_frames"
        )

        mocker.patch(
            "sys.argv",
            ["ap-move-master-to-library", str(source), str(dest), "--debug"],
        )

        main()

        call_args = mock_copy.call_args
        assert call_args.kwargs["debug"] is True

    def test_dryrun_flag(self, tmp_path, mocker):
        """Test --dryrun flag is correctly passed."""
        source = tmp_path / "source"
        dest = tmp_path / "dest"
        source.mkdir()
        dest.mkdir()

        mock_copy = mocker.patch(
            "ap_move_master_to_library.move_calibration.copy_calibration_frames"
        )

        mocker.patch(
            "sys.argv",
            ["ap-move-master-to-library", str(source), str(dest), "--dryrun"],
        )

        main()

        call_args = mock_copy.call_args
        assert call_args.kwargs["dryrun"] is True

    def test_no_overwrite_flag(self, tmp_path, mocker):
        """Test --no-overwrite flag is correctly passed."""
        source = tmp_path / "source"
        dest = tmp_path / "dest"
        source.mkdir()
        dest.mkdir()

        mock_copy = mocker.patch(
            "ap_move_master_to_library.move_calibration.copy_calibration_frames"
        )

        mocker.patch(
            "sys.argv",
            ["ap-move-master-to-library", str(source), str(dest), "--no-overwrite"],
        )

        main()

        call_args = mock_copy.call_args
        assert call_args.kwargs["no_overwrite"] is True

    def test_quiet_flag(self, tmp_path, mocker):
        """Test --quiet flag is correctly passed."""
        source = tmp_path / "source"
        dest = tmp_path / "dest"
        source.mkdir()
        dest.mkdir()

        mock_copy = mocker.patch(
            "ap_move_master_to_library.move_calibration.copy_calibration_frames"
        )

        mocker.patch(
            "sys.argv",
            ["ap-move-master-to-library", str(source), str(dest), "--quiet"],
        )

        main()

        # quiet is used for logging setup but not passed to copy function
        # This test verifies argparse accepts the flag
        mock_copy.assert_called_once()

    def test_quiet_short_flag(self, tmp_path, mocker):
        """Test -q (short form) flag works."""
        source = tmp_path / "source"
        dest = tmp_path / "dest"
        source.mkdir()
        dest.mkdir()

        mock_copy = mocker.patch(
            "ap_move_master_to_library.move_calibration.copy_calibration_frames"
        )

        mocker.patch(
            "sys.argv",
            ["ap-move-master-to-library", str(source), str(dest), "-q"],
        )

        main()

        # Verify -q is recognized as --quiet
        mock_copy.assert_called_once()

    def test_multiple_flags_combined(self, tmp_path, mocker):
        """Test --dryrun --debug --no-overwrite work together."""
        source = tmp_path / "source"
        dest = tmp_path / "dest"
        source.mkdir()
        dest.mkdir()

        mock_copy = mocker.patch(
            "ap_move_master_to_library.move_calibration.copy_calibration_frames"
        )

        mocker.patch(
            "sys.argv",
            [
                "ap-move-master-to-library",
                str(source),
                str(dest),
                "--dryrun",
                "--debug",
                "--no-overwrite",
            ],
        )

        main()

        call_args = mock_copy.call_args
        assert call_args.kwargs["dryrun"] is True
        assert call_args.kwargs["debug"] is True
        assert call_args.kwargs["no_overwrite"] is True

    def test_all_flags_combined(self, tmp_path, mocker):
        """Test all flags work together."""
        source = tmp_path / "source"
        dest = tmp_path / "dest"
        source.mkdir()
        dest.mkdir()

        mock_copy = mocker.patch(
            "ap_move_master_to_library.move_calibration.copy_calibration_frames"
        )

        mocker.patch(
            "sys.argv",
            [
                "ap-move-master-to-library",
                str(source),
                str(dest),
                "--dryrun",
                "--debug",
                "--quiet",
                "--no-overwrite",
            ],
        )

        main()

        call_args = mock_copy.call_args
        assert call_args.kwargs["dryrun"] is True
        assert call_args.kwargs["debug"] is True
        assert call_args.kwargs["no_overwrite"] is True
